### PR TITLE
Dont merge - Dustin's refactor part 1

### PR DESCRIPTION
**Pull request by dustingetz**

### CODE REVIEW

**Comment by dustingetz** [comment]
I screwed up and did this off of master instead of networked-pong, so i will need to redo it.

In the meantime, what do you think of these changes?
- busy work (splitting out files and cleaning up variables)
- interesting changes are in [index.js](https://github.com/dustingetz/aztec-pong/blob/59f769266f9ff8d1b14d65591afcb50b2dd0fd7a/src/index.js)
- I made everything into stateless function components to help indicate that we will never ever use a react lifecycle method - e.g. componentDidMount is not useful in aframe. shouldComponentUpdate is, maybe, the only exception to this. So it seems reasonable to prefer the function syntax rather than class syntax.
- I export an entrypoint fn, rather than calling ReactDOM.render inline, because source maps need to finish loading before we execute anything, otherwise debugging initialization is hard.

To understand the changes i would just start with [index.js](https://github.com/dustingetz/aztec-pong/blob/59f769266f9ff8d1b14d65591afcb50b2dd0fd7a/src/index.js) and explore the repo from there.

The next thing to refactor would be gameTick.

**Comment by meta-meta** [comment]
This is really great! I like the clean boundaries this sets up.

> componentDidMount is not useful in aframe

it is when we want to get at the underlying THREE object, but in general, I agree... I guess the ref callback eliminates the need though https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

> I export an entrypoint fn, rather than calling ReactDOM.render inline, because source maps need to 

finish loading before we execute anything, otherwise debugging initialization is hard.
I still don't totally get how source maps work. Could you explain next time we pair?

> The next thing to refactor would be gameTick.

Yes, this code is kind of gross, probably due to the dissonance of attempting to stick with setState() when it wasn't really applicable.

**Comment by dustingetz** [comment]
hi paul!

**Comment by meta-meta** [comment]
Hey Dustin, what's up? Time to port Aztec Pong to Hyperfiddle?

**Pull request closed without merging**
